config/routes.rb
Rails.application.routes.draw do

  get 'regcodes/new'
  post 'regcodes/create'
  get 'sessions/new'

  root 'static_pages#home'
  get 'static_pages/home'

  get 'static_pages/help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :ideas
  resources :regcodes
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/faq', to: 'static_pages#faq'
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :ideas, only: [:create, :update, :destroy, :index]
  post '/upvote', to: 'votes#upvote'
  get '/nav', to: 'application#nav'
  mount Thredded::Engine => '/forum'
end

app/models/regcode.rb
class Regcode < ApplicationRecord
	validates :code_digest,  presence: true, uniqueness: true
	def Regcode.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end
  	# Returns true if the given token matches the digest.
  	def authenticated?(code_token)
  		return false if code_digest.nil?
    	BCrypt::Password.new(code_digest).is_password?(code_token)
  	end

  	# Returns a random token.
	def Regcode.new_code
		SecureRandom.urlsafe_base64
	end
end

app/controllers/regcodes_controller.rb
class RegcodesController < ApplicationController
  def new
  	@regcode = Regcode.new
  end
  def create
    email = params['email']
    email = email.downcase

    if !email_valid? (email)
      flash[:danger] = "Please enter a valid email ending in @stanford.edu" 
      render 'new'  
    elsif email_exists? (email)
      flash[:danger] = "Email has already received registration code." 
      render 'new' 
    else
      code_token = Regcode.new_code
      @regcode = Regcode.new(code_digest: Regcode.digest(code_token) , used: false)

      if @regcode.save
        UserMailer.receive_regcode(email, code_token).deliver_now
        add_new_email(email)
        flash[:success] = "Success! A one-time registration link was sent to "+email
        redirect_to root_path
      else
        flash[:danger] = "Unable to generate new code please contact admin" 
        render 'new'  
      end

    end

  end
  
end

app/helpers/regcodes_helper.rb
module RegcodesHelper
	def regcode_for (code_token)
		if code_token == nil || code_token == ""
			return nil
		end
		Regcode.where(used: false).each do |rg|
			if rg.authenticated? (code_token)
				return rg
			end
		end
		nil
	end
end

app/views/regcodes/new.html.erb
<h1>Receive a registration code to sign up</h1>

<p> You will use your Stanford email to receive a registration code then use your registration code to sign up. This way you are an anonymous, verified Stanford student. We do not link your Stanford email address or  your registration code with your account. We only keep a hash of your email address and registration code for verification. The code for #stanfordlorax is open source and available here: <%= link_to "Github", "https://github.com/StanfordHCI/stanfordvisionplanning" %>. <%= link_to "Learn more", faq_path %>.
</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_tag(regcodes_create_path, method: "post") do %>
	  <%= label_tag(:email, "Stanford email:") %>
	  <%= text_field_tag(:email, "@stanford.edu", class: 'form-control' ) %>
	  <%= submit_tag("Receive registration code", class: "btn btn-primary") %>
	<% end %>
  </div>
</div>
<br><br><br>
<p>Stanford Lorax is a research project aimed at creating tools for distributed collaboration. By joining you agree to participate in this research. We may gather data and analyze your participation. All data will be anonymized before it is used for research. You may stop participating at any time by leaving the website, there will be no consequences.  While we cannot guarantee that you will receive any benefits from participating in the study, the potential benefits include submitting a proposal to Stanford vision planning. There is minimal risk associated with participating in this research.</p>

<p>You can read this message again at anytime by going to the FAQ page. If you have any questions contact us at stanford.lorax@gmail.com. If you have concerns about this research and would like to speak with someone independent of the research team, you may contact the Stanford IRB at irb2-manager@lists.stanford.edu.</p>