config/routes.rb
Rails.application.routes.draw do

  get 'regcodes/new'
  post 'regcodes/create'
  get 'sessions/new'

  root 'static_pages#home'
  get 'static_pages/home'

  get 'static_pages/help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :ideas
  resources :regcodes
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/faq', to: 'static_pages#faq'
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :ideas, only: [:create, :update, :destroy, :index]
  post '/upvote', to: 'votes#upvote'
  get '/nav', to: 'application#nav'
  mount Thredded::Engine => '/forum'
end

app/views/layouts/_forum_header.html.erb
<%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <!-- The mobile navbar-toggle button can be safely removed since you do not need it in a non-responsive implementation -->
          <%= link_to "#StanfordLorax", root_path, class:"navbar-brand", id: "logo", target:"_parent" %>
        </div>
        
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li> <%= link_to "Ideas", root_path, target:"_parent" %></li>
            <li ><%= link_to "FAQ", faq_path, target:"_parent" %></li>
            <li class="active"><%= link_to "Forum", "http://www.stanfordlorax.com/forum/ideas", target:"_parent" %></li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
     <%= link_to "#StanfordLorax", root_path, class:"navbar-brand", id: "logo" %>

  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li <% if current_page?(root_path) %> class="active" <% end %> > <%= link_to "Ideas", root_path %></li>
      <li <% if current_page?(faq_path) %> class="active" <% end %> ><%= link_to "FAQ", faq_path %></li>
      <li ><%= link_to "Forum", "http://www.stanfordlorax.com/forum/ideas" %></li>
      
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
      <li class="dropdown">

        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <b class="caret"></b></a>
        <ul class="dropdown-menu">
              
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
        </ul>
      </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>

      
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-100494575-1', 'auto');
    ga('send', 'pageview');

  </script>

  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>